# Generated by Django 4.0.1 on 2022-01-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=300)),
                ('pimg', models.TextField()),
                ('banner', models.TextField()),
                ('vname', models.CharField(max_length=300)),
                ('hname', models.CharField(max_length=300)),
                ('hdesc', models.TextField()),
                ('srtdesc', models.TextField()),
                ('lngdesc', models.TextField()),
                ('team', models.TextField()),
                ('itime', models.DateField()),
            ],
        ),
    ]
