# Generated by Django 4.0.1 on 2022-01-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0002_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
