# Generated by Django 4.0.1 on 2022-01-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0003_rename_jobs_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
