# Generated by Django 4.0.1 on 2022-01-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0005_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
