# Generated by Django 4.0.1 on 2022-01-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0009_rename_a_email_application_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Vacancy',
            new_name='vacancy',
        ),
    ]
