# Generated by Django 4.0.1 on 2022-01-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0010_rename_company_application_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
