# Generated by Django 4.0.1 on 2022-01-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0012_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='cname',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
